Abort with an hopefully informative error message if GNUSTEP_SYSTEM_ROOT is undefined
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/base/trunk@9785 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -24,6 +24,13 @@ AC_INIT(Source/NSArray.m)
 #   License along with this library; if not, write to the Free
 #   Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111 USA
 
+if test -z "$GNUSTEP_SYSTEM_ROOT"; then
+  {
+   echo "ERROR: You must run the GNUstep initialization script before configuring the base library!" 1>&2;
+  exit 1; 
+  }
+fi
+
 #--------------------------------------------------------------------
 # Use a .h file with #define's, instead of -D command-line switches
 #--------------------------------------------------------------------
