* configure.ac: Test for objc forwarding by compiling a program. * config/config.forward.m: New file. (Fixes bug #11188).
* Source/GSFormat.m (GSFormat): Assign wchar via var args from an
int (Fixes bug #10950).

* Testing/string.m: Tests for standardizing path.


git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/base/trunk@20427 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13844,24 +13844,40 @@ have_forward_hook=yes
 echo "$as_me:$LINENO: checking \"for forwarding callback in runtime\"" >&5
 echo $ECHO_N "checking \"for forwarding callback in runtime\"... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
+#include "$srcdir/config/config.forward.m"
 _ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <objc/objc-api.h>
-
-_ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  $EGREP "__objc_msg_forward" >/dev/null 2>&1; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_forward_hook=yes
 else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; have_forward_hook=no
-fi
-rm -f conftest*
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
 
+have_forward_hook=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $have_forward_hook" >&5
+echo "${ECHO_T}$have_forward_hook" >&6
 if test $have_forward_hook = no; then
   enable_libffi=no
   enable_ffcall=no
