Improved --with-installation-domain=xxx configure option, and fixed support for installation-domains.conf file
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/base/trunk@27414 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -914,13 +914,18 @@ Optional Packages:
 				then the path from --with-config-file or from
 				the gnustep-make package is used.
   --with-installation-domain=DOMAIN
-Specify the domain (SYSTEM, LOCAL, NETWORK
-or USER) into which gnustep-base will be installed.  This is
-necessary whenever because relative paths
-are hardcoded into gnustep-base.  If this is not specified, LOCAL
-is used.  Please make sure this matches the DOMAIN where
-you will be installing gnustep-base to prevent problems
-with finding resources at runtime.
+				Specify the domain (SYSTEM, LOCAL,
+				NETWORK or USER) into which
+				gnustep-base will be installed.
+				Whenever relative paths are hardcoded
+				into gnustep-base (at the moment, this
+				happens only on MinGW) this option
+				must be used and must match the domain
+				where you will be installing
+				gnustep-base.
+				If this is not specified, the output of
+				gnustep-config --installation-domain-for=gnustep-base
+				(which should normally be LOCAL) is used.
   --with-include-flags=FLAGS    Specify all include flags at once
   --with-library-flags=FLAGS    Specify all library flags at once
   --with-ffi-include=PATH       Include path for ffi (ffcall/libffi) headers
@@ -1804,9 +1809,25 @@ if test "${with_installation_domain+set}" = set; then
   withval="$with_installation_domain"
   result="$withval"
 else
-  result="$GNUSTEP_INSTALLATION_DOMAIN"
+  result="no"
 
 fi;
+if test "$result" == "no"
+then
+  # Check if gnustep-config supports the option
+  # --installation-domain-for, and use it if available.  That option
+  # will automatically use the shell variable GNUSTEP_INSTALLATION_DOMAIN
+  # or the installation-domains.conf files (or the LOCAL default) as appropriate.
+  # Otherwise, if that option is not available just fall back to LOCAL.
+  if (gnustep-config --help | grep installation-domain) >&5 2>&5
+  then
+    result=`gnustep-config --installation-domain-for=gnustep-base 2>&5`
+  else
+    # This case was added on December 2008 and is only for backwards
+    # compatibility with older versions of gnustep-make.
+    result=LOCAL
+  fi
+fi
 case "$result" in
   SYSTEM)
     echo "$as_me:$LINENO: result: SYSTEM" >&5
@@ -1825,11 +1846,14 @@ echo "${ECHO_T}NETWORK" >&6
 echo "${ECHO_T}USER" >&6
     GNUSTEP_BASE_PATH="$GNUSTEP_USER_TOOLS";;
   *)
-    echo "$as_me:$LINENO: result: none specified => using LOCAL" >&5
-echo "${ECHO_T}none specified => using LOCAL" >&6
-    result=LOCAL;
-    GNUSTEP_BASE_PATH="$GNUSTEP_LOCAL_TOOLS";;
+    { { echo "$as_me:$LINENO: error: Unknown installation domain '$result' (it should be SYSTEM, LOCAL, NETWORK or USER).  Please run configure again with the option --with-installation-domain=LOCAL (or whatever domain you want to install into)." >&5
+echo "$as_me: error: Unknown installation domain '$result' (it should be SYSTEM, LOCAL, NETWORK or USER).  Please run configure again with the option --with-installation-domain=LOCAL (or whatever domain you want to install into)." >&2;}
+   { (exit 1); exit 1; }; }
+    exit 1;;
 esac
+# We store GNUSTEP_BASE_DOMAIN in config.mak so that we can check
+# at runtime and make sure it is consistent with the
+# GNUSTEP_INSTALLATION_DOMAIN that is used at runtime.
 GNUSTEP_BASE_DOMAIN=$result
 
 
