Add test for presence of __objc_msg_forward2
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/base/trunk@25059 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15985,6 +15985,42 @@ CPPFLAGS="$CPPFLAGS $OBJCFLAGS -x objective-c"
 { echo "$as_me:$LINENO: checking for forwarding callback in runtime" >&5
 echo $ECHO_N "checking for forwarding callback in runtime... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
+#include "$srcdir/config/config.forward2.m"
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  have_forward_hook=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	have_forward_hook=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+if test $have_forward_hook = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FORWARD2 1
+_ACEOF
+
+else
+  cat >conftest.$ac_ext <<_ACEOF
 #include "$srcdir/config/config.forward.m"
 _ACEOF
 rm -f conftest.$ac_objext
@@ -16013,6 +16049,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
 { echo "$as_me:$LINENO: result: $have_forward_hook" >&5
 echo "${ECHO_T}$have_forward_hook" >&6; }
 if test $have_forward_hook = no; then
