Tidied GSDoc to compile nicely for libxml
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/base/trunk@6736 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4325,6 +4325,88 @@ EOF
 fi
 
 
+#--------------------------------------------------------------------
+# Check recent libxlm for GSDoc etc.
+#--------------------------------------------------------------------
+echo "Checking for libxml"
+for ac_hdr in libxml/xmlversion.h
+do
+ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
+echo "configure:4337: checking for $ac_hdr" >&5
+if eval "test \"\${ac_cv_header_$ac_safe+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 4342 "configure"
+#include "confdefs.h"
+#include <$ac_hdr>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:4347: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+    ac_tr_hdr=HAVE_`echo $ac_hdr | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_hdr 1
+EOF
+ 
+else
+  echo "$ac_t""no" 1>&6
+fi
+done
+
+if test $ac_cv_header_libxml_xmlversion_h = no; then
+  echo "Could not find libxml headers"
+  echo "Check to make sure you have libxml version 2 or later installed"
+  echo "configure: warning: Could not find libxml headers" 1>&2
+  HAVE_LIBXML=0
+else
+  cat > conftest.$ac_ext <<EOF
+#line 4380 "configure"
+#include "confdefs.h"
+#include "libxml/xmlversion.h"
+    #if LIBXML_VERSION < 20000
+    #error
+    #endif
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:4388: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  libxml2plus=1
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  libxml2plus=0
+fi
+rm -f conftest*
+  if test $libxml2plus = 0; then
+    echo "libxml version older than 2.0.0"
+    echo "configure: warning: libxml version older than 2.0.0" 1>&2
+    HAVE_LIBXML=0
+  else
+    HAVE_LIBXML=1
+  fi
+fi
+
+
 
 
 
@@ -4518,6 +4600,7 @@ s%@_GSC_S_LNG@%$_GSC_S_LNG%g
 s%@_GSC_S_LNG_LNG@%$_GSC_S_LNG_LNG%g
 s%@DYNAMIC_LINKER@%$DYNAMIC_LINKER%g
 s%@GS_FAKE_MAIN@%$GS_FAKE_MAIN%g
+s%@HAVE_LIBXML@%$HAVE_LIBXML%g
 s%@whole_archive@%$whole_archive%g
 s%@no_whole_archive@%$no_whole_archive%g
 s%@subdirs@%$subdirs%g
