Thread safety for openssl
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/base/trunk@29664 72102866-910b-0410-8b05-ffd578937521

diff --git a/SSL/configure b/SSL/configure
--- a/SSL/configure
+++ b/SSL/configure
@@ -3635,6 +3635,97 @@ fi
       if test $ac_cv_lib_ssl_ssl2_clear = yes; then
         ssl_ok=yes
       fi
+      echo "$as_me:$LINENO: checking for CRYPTO_THREADID_set_callback" >&5
+echo $ECHO_N "checking for CRYPTO_THREADID_set_callback... $ECHO_C" >&6
+if test "${ac_cv_func_CRYPTO_THREADID_set_callback+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define CRYPTO_THREADID_set_callback to an innocuous variant, in case <limits.h> declares CRYPTO_THREADID_set_callback.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define CRYPTO_THREADID_set_callback innocuous_CRYPTO_THREADID_set_callback
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char CRYPTO_THREADID_set_callback (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef CRYPTO_THREADID_set_callback
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char CRYPTO_THREADID_set_callback ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_CRYPTO_THREADID_set_callback) || defined (__stub___CRYPTO_THREADID_set_callback)
+choke me
+#else
+char (*f) () = CRYPTO_THREADID_set_callback;
+#endif
+#ifdef __cplusplus
+}
+#endif
+
+int
+main ()
+{
+return f != CRYPTO_THREADID_set_callback;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_func_CRYPTO_THREADID_set_callback=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_func_CRYPTO_THREADID_set_callback=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_func_CRYPTO_THREADID_set_callback" >&5
+echo "${ECHO_T}$ac_cv_func_CRYPTO_THREADID_set_callback" >&6
+
     fi
   fi
   if test $ssl_ok = no; then
