* SSL/configure.ac: Check for GNUSTEP_MAKEFILES not GNUSTEP_SYSTEM_ROOT.
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/libs/base/trunk@22189 72102866-910b-0410-8b05-ffd578937521

diff --git a/SSL/configure b/SSL/configure
--- a/SSL/configure
+++ b/SSL/configure
@@ -1304,9 +1304,9 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-if test -z "$GNUSTEP_SYSTEM_ROOT"; then
-  { { echo "$as_me:$LINENO: error: You must run the GNUstep initialization script first!" >&5
-echo "$as_me: error: You must run the GNUstep initialization script first!" >&2;}
+if test -z "$GNUSTEP_MAKEFILES"; then
+  { { echo "$as_me:$LINENO: error: You must have the gnustep-make package installed and set up the GNUSTEP_MAKEFILES environment variable to contain the path to the makefiles directory before configuring!" >&5
+echo "$as_me: error: You must have the gnustep-make package installed and set up the GNUSTEP_MAKEFILES environment variable to contain the path to the makefiles directory before configuring!" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
